name: test

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run a test to check if models are working
      run: |
        for model_number in 1 2 3
        do
          for model_size in small big
          do
            for model_average in 1 5 10 20
            do
              python predict.py --input-file-path sample_input \
                                --model-type rnn \
                                --model-number $model_number \
                                --model-size $model_size \
                                --model-average $model_average \
                                --output-file-path sample_output
              test -e sample_output
              rm -f sample_output
            done
          done
          python predict.py --input-file-path sample_input \
                            --model-type ffnn \
                            --model-number $model_number \
                            --output-file-path sample_output
          test -e sample_output
          rm -f sample_output
        done