name: test

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        model_type: [rnn, ffnn]
        model_number: [1, 2, 3]
        model_size: [small, big]
        model_average: [1, 5, 10, 20]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run a test to check if rnn models are working
      run: python predict.py --input-file-path sample_input \
                             --model-type rnn \
                             --model-number ${{ matrix.model_number }} \
                             --model-size ${{ matrix.model_size }} \
                             --model-average ${{ matrix.model_average }} \
                             --output-file-path sample_output
           test -e sample_output

    - name: Run a test to check if ffnn models are working
      run: python predict.py --input-file-path sample_input \
                             --model-type ffnn \
                             --model-number ${{ matrix.model_number }} \
                             --output-file-path sample_output
           test -e sample_output